# Generated by Django 3.1.6 on 2021-02-06 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='head',
            field=models.CharField(max_length=200, verbose_name='head'),
        ),
        migrations.AlterField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nestedpages.page'),
        ),
    ]
