# Generated by Django 3.1.6 on 2021-02-06 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nestedpages', '0002_auto_20210206_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent',
        ),
        migrations.AddField(
            model_name='page',
            name='parent_url',
            field=models.CharField(max_length=100, null=True, verbose_name='Parrent URL'),
        ),
        migrations.AlterField(
            model_name='page',
            name='url',
            field=models.CharField(max_length=100, verbose_name='URL'),
        ),
    ]
