# Generated by Django 3.1.6 on 2021-02-07 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nestedpages', '0003_auto_20210206_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='parent_url',
        ),
        migrations.AddField(
            model_name='page',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='nestedpages.page'),
        ),
    ]
